# Generated by Django 2.2.5 on 2019-09-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the task in maximum 120 signs.', max_length=120)),
                ('start_date', models.DateTimeField(help_text='Scheduled start time of the task.', null=True)),
                ('end_date', models.DateTimeField(help_text='Scheduled start time of the task.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.Task')),
            ],
            options={
                'order_with_respect_to': 'parent',
            },
        ),
    ]
